# permissions for end users to view netconfs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: network-operator
    app.kubernetes.io/managed-by: kustomize
  name: netconf-viewer-role
rules:
- apiGroups:
  - network.digicloud.ir
  resources:
  - netconfs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - network.digicloud.ir
  resources:
  - netconfs/status
  verbs:
  - get
